WbArch:
  active: true

  MissingArcLayerRule:
    active: true
  ModuleDependencyRule:
    active: true
  ImplementationIsolationRule:
    active: true

  SeparateDataModelPerLayerRule:
    active: true
  ModelMappingRule:
    active: true

  NoStateInRepositoryRule:
    active: true
  RepositoryMethodNamingRule:
    active: true
  SingleSourceRepositoryRule:
    active: true
  RepositoryReturnsResultInWrapperRule:
    active: true

  SingleMethodInUseCaseRule:
    active: true
  UseCaseNoRepositoryDependencyRule:
    active: true

  ViewStateUpdateThroughUpdateMethodRule:
    active: true
  ViewStateClassRule:
    active: true

WbCompose:
  active: true

  NoDirectColorUseRule:
    active: true
  NoCollectAsStateRule:
    active: true
  StringsMustBeConstantsOrResourceRule:
    active: true

WbCoroutines:
  active: true

  NoManualCoroutineScopeRule:
    active: true
  FlowSubscriptionInViewModelRule:
    active: true

WbDI:
  active: true

  NoKoinModuleInAppModuleRule:
    active: true
  NoDependencyInjectionWithByInjectRule:
    active: true
  KoinModuleMustHaveScopeRule:
    active: true

WbNavigation:
  active: true

  NavigationGraphsMustBeDividedIntoSubgraphsRule:
    active: true
  NavigationWithSingleArgumentRule:
    active: true

WbTests:
  active: true

  StubsNotMocksInTestsRule:
    active: true
  RecreateSUTForEachTestRule:
    active: true
#  BeforeAnnotationInTestRule:
#    active: test

