WBCustomRules:
  active: true

  MissingArcLayerRule:
    active: true
  ModuleDependencyRule:
    active: true
  ImplementationIsolationRule:
    active: true

  SeparateDataModelPerLayerRule:
    active: true
  ModelMappingRule:
    active: true

  NoStateInRepositoryRule:
    active: true
  RepositoryMethodNamingRule:
    active: true
  SingleSourceRepositoryRule:
    active: true
  RepositoryReturnsResultInWrapperRule:
    active: true

  SingleMethodInUseCaseRule:
    active: true
  UseCaseNoRepositoryDependencyRule:
    active: true

  ViewStateUpdateThroughUpdateMethodRule:
    active: true
  ViewStateClassRule:
    active: true

  NoManualCoroutineScopeRule:
    active: true
  FlowSubscriptionInViewModelRule:
    active: true

  KoinModulesDistributionRule:
    active: true
  NoByInjectRule:
    active: true
  KoinModuleScopeRule:
    active: true

  NoDirectColorUseRule:
    active: true
  NoCollectAsStateInComposableRule:
    active: true

  NavigationGraphSubgraphRule:
    active: true
  NoExtraParamsInNavigationRule:
    active: true

  UseStubsInTestsRule:
    active: true
  RecreateSutRule:
    active: true
  BeforeAnnotationInTest:
    active: test
